runtime: go121
env: standard
app_engine_apis: true

main: .

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /.*
  script: auto 